#+title: Org mode

Install Org mode to prevent version mismatches between the Org bundled with Emacs and the dependencies of other packages.

#+name: org-use-package
#+headers: :exports none
#+begin_src emacs-lisp
  (use-package org
#+end_src

#+headers: :noweb yes
#+begin_src emacs-lisp
  <<org-use-package>>)
#+end_src

* =org-cycle-separator-lines=

#+include: "emacs-org-cycle-separator-lines.org" :lines "8-"

#+name: org-custom-separator-lines
#+headers: :exports none
#+begin_src emacs-lisp
  (org-cycle-separator-lines -1)
#+end_src

* Org-agenda

Configure Org to recursively look through =~/notes/= for displaying the agenda:

#+name: org-custom-agenda
#+headers: :exports none
#+begin_src emacs-lisp
  (org-agenda-files (directory-files-recursively "~/notes/" "\\.org$"))
#+end_src

#+headers: :noweb yes
#+begin_src emacs-lisp
  <<org-use-package>>
    :custom
    <<org-custom-agenda>>)
#+end_src

* Org-babel

[[https://orgmode.org/worg/org-contrib/babel/][Org-babel]] executes source code within Org documents.
It only supports Emacs Lisp by default, but more languages can be added to =org-babel-load-languages=:

#+name: org-custom-babel
#+headers: :exports none
#+begin_src emacs-lisp
  (org-babel-load-languages '((emacs-lisp . t)
                              (shell . t)))
#+end_src

#+headers: :noweb yes
#+begin_src emacs-lisp
  <<org-use-package>>
    :custom
    <<org-custom-babel>>)
#+end_src

#+headers: :tangle org.el
#+headers: :noweb yes
#+headers: :exports none
#+begin_src emacs-lisp
  <<org-use-package>>
    :custom
    <<org-custom-separator-lines>>
    <<org-custom-agenda>>
    <<org-custom-babel>>)
#+end_src


* Org-gtd.el
:PROPERTIES:
:CUSTOM_ID: org-gtd
:END:

[[https://github.com/Trevoke/org-gtd.el][Org-gtd.el]] is an implementation of "Getting Things Done" in Emacs.

Set the =org-gtd-update-ack= variable to prevent a warning about upgrading from being printed when org-gtd loads.

#+headers: :exports none
#+begin_src
 ■  Warning (org-gtd):

|--------------------------|
| WARNING: action required |
|--------------------------|

Upgrading to 2.1.0 requires changing the org-edna triggers for the project
categories. Failure to do so means your projects will end up in inconsistent
states.

See the documentation for instructions to upgrade (C-h i, then find org-gtd),
then add the following setting to your config file (BEFORE ORG-GTD LOADS)
to disable this warning.

(setq org-gtd-update-ack "2.1.0")
#+end_src

#+begin_src emacs-lisp :tangle org.el
  (use-package org-gtd
    :init
    (setq org-gtd-update-ack "2.1.0"))
#+end_src


* Org-auto-tangle
:PROPERTIES:
:CUSTOM_ID: org-auto-tangle
:END:

[[https://github.com/yilkalargaw/org-auto-tangle][Org-auto-tangle]] automatically tangles Org files on save.

Be default, it only auto-tangles files marked with the =#+auto_tangle= header option.
By turning on =org-auto-tangle-default=, org-auto-tangle tangles all Org files, even without that option.

#+begin_src emacs-lisp :tangle org.el
  (use-package org-auto-tangle
    :hook
    (org-mode . org-auto-tangle-mode)
    :custom
    (org-auto-tangle-default t))
#+end_src
